### ISSUE TITLE
Client crash on Windows 

### ISSUE THREAD

**Issue by hawka97** [Mica-Technologies/Minecraft-Forge-Launcher#41]
When launching a modpack, the launcher stops at "Fetching Minecraft assets, libraries and classpath" on the loading progress screen. Running with `java -jar [launcher-file-full-path].jar` gives the following output:

`[Mica Forge Launcher/LOG] Inferred client mode
Exception in thread "Thread-6" java.lang.IllegalArgumentException: character to be escaped is missing
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182)
        at java.base/java.lang.String.replaceAll(String.java:2126)
        at com.micatechnologies.minecraft.forgemodpacklib.MCRemoteFile.<init>(MCRemoteFile.java:71)
        at com.micatechnologies.minecraft.forgemodpacklib.MCLibrary.<init>(MCLibrary.java:46)
        at com.micatechnologies.minecraft.forgemodpacklib.MCLibraryManifest.getLibraries(MCLibraryManifest.java:163)
        at com.micatechnologies.minecraft.forgemodpacklib.MCLibraryManifest.buildMinecraftClasspath(MCLibraryManifest.java:314)
        at com.micatechnologies.minecraft.forgemodpacklib.MCForgeModpack.buildModpackClasspath(MCForgeModpack.java:283)
        at com.micatechnologies.minecraft.forgemodpacklib.MCForgeModpack.startGame(MCForgeModpack.java:303)
        at com.micatechnologies.minecraft.forgelauncher.MCFLApp.playClient(MCFLApp.java:278)
        at com.micatechnologies.minecraft.forgelauncher.MCFLApp.play(MCFLApp.java:221)
        at com.micatechnologies.minecraft.forgelauncher.MCFLModpacksGUI.lambda$create$9(MCFLModpacksGUI.java:153)
        at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by hawka97** [comment]
fixed in 8eda8bef1407c2f18ef603964222ba4d66f1dc63
